image: docker

services:
  - docker:dind

stages:
  - test

test:
  stage: test
  script:
    - make build-testimage
    - docker-compose up -d
    - docker-compose exec api bash
    - whoami
    - which python3.10
    - poetry run pytest
    - exit

lint:
  stage: test
  script:
    - python --version
    - pip --version
    - pip install pre-commit
    - pre-commit --version
    - make lint
