image: docker

services:
  - docker:dind

stages:
    - test


test:
    stage: test
    script: 
        - make test

lint:
    stage: test
    script:
      - python --version
      - pip --version
      - pip install pre-commit
      - pre-commit --version
      - make lint