image: docker

services:
  - docker:dind

stages:
    - lint
    - test


test:
    stage: test
    script: 
        - make test

lint:
    stage: lint
    script:
      - python --version
      - pip --version
      - poetry --version
      - pip install pre-commit
      - python -m pre-commit --version
      - make lint