image: docker

services:
  - docker:dind

stages:
    - test


test:
    stage: test
    script: 
        - make build
        - docker-compose up -d
        - docker ps -a
        - docker-compose exec api bash
        - whoami
        - python -m pytest
        - exit
        - docker-compose down

lint:
    stage: test
    script:
      - python --version
      - pip --version
      - pip install pre-commit
      - pre-commit --version
      - make lint