version: "3.9"
services:
  api:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db
    
  db:
    image: postgres
    ports:
      - 8001:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: