version: "3.9"
services:
  api:
    build: .
    volumes:
      - .:/code
    ports:
      - 80:8000
    env_file:
      - .env_prod
    stdin_open: true
    tty: true
    depends_on:
      - db
    
  db:
    build:
      dockerfile: Dockerfile_db
      context: .
    ports:
      - 8001:5432
    env_file:
      - .env_prod
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: